apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: managed-nfs-storage
provisioner: storage.blibli.future/nfs
parameters:
  pathPattern: "${.PVC.namespace}-${.PVC.name}"
reclaimPolicy: Retain