---
# tasks file for docker
- name: check docker version
  include: check.yml

- name: install docker server version
  include: install.yml
  when: docker_client_version.stdout | length == 0 or docker_client_version.stdout != docker_server_version 
