---
# defaults file for Docker
kubernetes_user_version: 1.21.1
type: Master
kubernetes_server_ip: 
kubernetes_server_name:
kubernetes_server_network:
config: True
apply: False
port_master:
  - 6443
  - "2379-2380"
  - 10250
  - 10251
  - 10252
port_worker:
  - 10250
  - "30000-32767"