---
kind: Service
apiVersion: v1
metadata:
  name: node-exporter
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port: '9100'
  namespace: monitoring
spec:
  selector:
      component: exporter
      name: node-exporter
  ports:
  - name: node-exporter
    protocol: TCP
    port: 9100
    targetPort: 9100